### ISSUE TITLE
Fox

### ISSUE THREAD

**Issue by Arkadia2008** [MetalChris/repository.metalchris#23]
I hate to be the bearer of bad news, but Fox seems to be broken again.

` Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Uta\AppData\Roaming\Kodi\addons\plugin.video.fox\addon.py", line 305, in <module>
                                                FOX_videos(name,url)
                                              File "C:\Users\Uta\AppData\Roaming\Kodi\addons\plugin.video.fox\addon.py", line 76, in FOX_videos
                                                season = soup[0].text.split(' ')[-1]
                                            IndexError: list index out of range`

**Comment by MetalChris** [comment]
Ugh.  This one breaks every couple of weeks.  I'm probably not going to fix it again because Fox just won't stop screwing around with their website.
